[package]
name = "dico-desktop"
version = "1.0.4"
description = "Dico — French dictionary popup (Windows / Linux / macOS)"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png", "protocol-asset", "macos-private-api"] }
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
